- src/App.jsx
- src/App.scss
- src/Pages/logIn/Login.jsx
- src/Pages/logIn/Login.scss
1. pages->login폴더의 loginLogin.jsx 와 Login.scss를 추가했습니다. 
2. App.jsx import 경로가 잘못되어있어서 수정했습니다.
3. App.scss에 blind 스타일을 추가하였습니다.
> Feature/login Login 컴포넌트 및 스타일 추가, App.jsx import 경로 수정

- src/Pages/signUp/button/Button.jsx
- src/Pages/signUp/contexts/UserContext.jsx
- src/Pages/signUp/profileSet/ProfileSet.jsx
- src/Pages/signUp/signUp.jsx
회원가입 페이지에서 '시작하기' 버튼 클릭 시 서버로 POST 요청 보내는 기능을 구현했습니다.
입력 폼 유효성 검사, 데이터 중복 검사 기능 추가로 작업 예정입니다.
> 🔧 useContext 이용하여 회원가입 정보 POST 기능 구현

- src/Components/scss/reset.scss
크롬 기본 인풋창 백그라운드 컬러 Reset 하였습니다.
> 🎨 크롬 인풋창 기본스타일 리셋

- src/Components/splash/Splash.jsx
- src/Pages/logIn/signUp/SignUp.scss
- src/Pages/logIn/signUp/emailSignUp/SetAccount.jsx
- src/Pages/logIn/signUp/profileSet/EditInfo.jsx
- src/Pages/logIn/signUp/profileSet/UploadPic.jsx
- src/Pages/logIn/signUp/profileSet/profileSet.scss
회원가입 컴포넌트의 이메일 검증 기능과 비밀번호 유효성 검사 기능을 추가하였습니다.
> 🔧 회원가입 계정 검증 기능 추가

- src/App.jsx
- src/Pages/home/Home.jsx
- src/Pages/home/Home.scss
- src/Pages/logIn/emailLogin/EmailLogin.jsx
- src/Pages/logIn/emailLogin/EmailLogin.scss
- src/Pages/logIn/signUp/SignUp.jsx
- src/Pages/logIn/signUp/SignUp.scss
1. .App에 적용될 스타일 코드를 Home.scss 로 경로 이동
2. useState가 없어진 상태로 merge 돼서 오류난 코드 수정
3. 라우터 버전6에 맞게 useHistory->useNavigate
> 🧹 스타일 코드 경로, 라우터, 오류 코드 변경

- src/Pages/logIn/emailLogin/Button.scss
- src/Pages/logIn/emailLogin/EmailLogin.jsx
- src/Pages/logIn/emailLogin/EmailLogin.scss
1. 로그인 실패시 오류메세지 리팩토링 
2. 함수명 통일 
3. 인풋 포커징 기능
> 🔧로그인페이지 추가 기능 구현 및 리팩토링

- src/Pages/logIn/signUp/SignUp.jsx
- src/Pages/logIn/signUp/SignUp.scss
- src/Pages/logIn/signUp/emailSignUp/SetAccount.jsx
- src/Pages/logIn/signUp/profileSet/EditInfo.jsx
- src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
- src/Pages/logIn/signUp/profileSet/UploadPic.jsx
- src/Pages/logIn/signUp/profileSet/profileSet.scss
1. 프로필사진 서버로 보내는 기능, 미리보기 기능 추가하였습니다.
> 🔧 프로필 사진 첨부 기능 추가

- src/Pages/home/Home.jsx
- src/Pages/logIn/signUp/SignUp.jsx
- src/Pages/logIn/signUp/SignUp.scss
- src/Pages/logIn/signUp/emailSignUp/SetAccount.jsx
- src/Pages/logIn/signUp/profileSet/EditInfo.jsx
- src/Pages/logIn/signUp/profileSet/UploadPic.jsx
프로필 사진 요청 url 맞게 수정하였습니다. 이제 파일 첨부 잘 됩니다! 프로필 사진이 없을 경우 기본이미지 보여주도록 저희 부모컴포넌트에서 설정해둬야 할 것 같습니다.
> 🧹 에러메세지 css수정, 프로필 사진 첨부 오류 수정

- src/Pages/logIn/Button.jsx
- src/Pages/logIn/Button.scss
- src/Pages/logIn/emailLogin/EmailLogin.scss
- src/Pages/logIn/signUp/SignUp.scss
- src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
- src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
로그인 회원가입 페이지의 버튼을 통일, 이에 따른 경로 수정
> ♻️ 로그인 회원가입페이지 버튼 컴포넌트화 

- src/Pages/logIn/Button.jsx
- src/Pages/logIn/emailLogin/EmailLogin.jsx
- src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
- src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
- 로그인 후 splash 페이지 나온 후에 home 이동
- 로그인, 로그아웃 버튼 속성명 form -> name 으로 변경
> ♻️ 로그인 후 스플레시 페이지 구현 , 버튼 속성명 변경

- src/Components/footer/ChatroomFooter.jsx
- src/Components/footer/CommentFooter.jsx
- src/Components/footer/MainFooter.scss
- src/Components/footer/PageFooter.scss
- src/Components/footer/TabmenuList.jsx
- src/Components/footer/TabmenuList.scss
1. footer 스타일과 컨벤션 순서에 맞게 수정 했습니다.
2. 하단 탭이 페이지 경로에 해당하면 탭이  활성화가 되도록 구현 했습니다.
> footer 스타일 수정 및 하단 탭 활성화 기능 추가

- src/App.jsx
> ♻️ 라우팅 경로 변경

- src/Pages/product/Product.jsx
- src/Pages/product/Product.scss
- src/Pages/profileEdit/ProfileEdit.jsx
- src/Pages/profileEdit/ProfileEdit.scss
1. ProfileEdit UI 구현
2. Product Ui 구현
> 🎨: ProfileEdit, Product UI 구현

- src/App.jsx
- src/Components/button/UploadIconBtn.jsx
- src/Components/footer/ChatroomFooter.jsx
- src/Components/footer/CommentFooter.jsx
- src/Components/footer/MainFooter.jsx
- src/Components/footer/MainFooter.scss
- src/Components/footer/PageFooter.scss
- src/Components/footer/TabmenuList.jsx
- src/Components/footer/TabmenuList.scss
- src/Components/splash/Splash.jsx
- src/Components/splash/Splash.scss
- src/Pages/product/Product.jsx
- src/Pages/product/Product.scss
- src/Pages/product/ProductInput.jsx
- src/Pages/uploadPost/UploadPost.jsx
- src/Pages/uploadPost/UploadPost.scss
1. 컨벤션에 맞게 코드 수정
2. uploadPost 폴더생성 및 경로 설정
> 컨벤션에 맞게 코드수정

- src/App.jsx
- src/Components/button/FollowBtn.jsx
- src/Components/button/FollowBtn.scss
- src/Components/splash/Splash.scss
- src/Pages/chat/chatPage/ChatItem.jsx
- src/Pages/chat/chatPage/ChatItem.scss
- src/Pages/chat/chatPage/ChatPage.jsx
- src/Pages/chat/chatPage/ChatPage.scss
- src/Pages/chat/chatRoom/ChatRoom.jsx
- src/Pages/chat/chatRoom/ChatRoom.scss
- src/Pages/chat/chatRoom/Chatting.jsx
- src/Pages/chat/chatRoom/GetMessage.jsx
- src/Pages/chat/chatRoom/Message.scss
- src/Pages/chat/chatRoom/SendMessage.jsx
- src/Pages/follow/Follow.scss
- src/Pages/follow/FollowUser.jsx
- src/Pages/follow/Followers.jsx
- src/Pages/follow/Followings.jsx
- src/Pages/profile/Profile.scss
- src/Pages/profile/UserProfile.jsx
> HTML , CSS 컨벤션 적용

- src/Pages/uploadPost/UploadPost.jsx
- src/Pages/uploadPost/UploadPost.scss
1. UploadPost Textarea 높이가 컨텐츠의 높이에 맞게 자동으로 늘어나고 줄어들도록 수정
> 🎨: UploadPost의 Textarea 높이를 반응형으로 수정

- src/App.jsx
- src/Pages/notFound/NotFound.jsx
- src/Pages/notFound/NotFound.scss
> 🔧 NotFound 페이지 구현 

- src/assets/icon-x.svg
- src/pages/uploadPost/PhotoList.jsx
- src/pages/uploadPost/PhotoList.scss
- src/pages/uploadPost/UploadPost.jsx
- src/pages/uploadPost/UploadPost.scss
1. Upload 버튼 포인터 추가
2. 이미지 영역 추가
3. 레이아웃 수정
4. PhotoList 파일 생성
> 🎨: UploadPost 페이지 레이아웃, 스타일 수정

- src/components/header/SearchHeader.jsx
- src/components/user/UserInfoBox.scss
- src/pages/home/userSearch/SearchResult.jsx
- src/pages/home/userSearch/UserSearch.jsx
우선 기능검색구현이 작동하는지 확인하시면 됩니다. 추후 useContext이용, 프로필이미지 반영 추가 하겠습니다~~
> 🔧 검색기능구현 추가. 추후 이미지, useContext추가 및 scss 수정 예정

- src/App.jsx
- src/components/button/FollowBtn.jsx
- src/components/button/FollowBtn.scss
- src/components/footer/MainFooter.jsx
- src/components/user/UserInfoBox.jsx
- src/pages/chat/chatRoom/GetMessage.jsx
- src/pages/follow/Follow.scss
- src/pages/follow/FollowUser.jsx
- src/pages/follow/Followers.jsx
- src/pages/follow/Followings.jsx
- src/pages/home/userSearch/SearchResult.jsx
- src/pages/logIn/emailLogin/EmailLogin.jsx
- src/pages/logIn/signUp/SignUp.jsx
- src/pages/logIn/signUp/profileSet/ProfileSet.jsx
- src/pages/logIn/signUp/profileSet/UploadPic.jsx
- src/pages/profile/MyProfile.jsx
- src/pages/profile/UserProfile.jsx
- src/pages/profile/profileHeader/ProfileHeader.jsx
1. 서버에서 팔로잉, 팔로우 리스트 데이터 불러오는 기능 추가
2. 팔로우,언팔로우 기능 추가, count up&down 기능 추가
3. profile/accountname 이었던 라우트를 /accountname으로 변경
4. 기본 프로필 이미지 변경
> 🔧 팔로잉, 팔로우 기능 구현

- src/App.jsx
- src/components/button/SaveBtn.jsx
- src/components/header/SaveHeader.jsx
- src/components/splash/Splash.jsx
- src/context/SplashContext.jsx
- src/context/UserContext.jsx
- src/pages/home/Home.jsx
- src/pages/profileEdit/ProfileEdit.jsx
- src/pages/profileEdit/ProfileEdit.scss
- src/pages/profileEdit/ProfileEditInfo.jsx
- src/pages/profileEdit/ProfileEditUpload.jsx
1. userContext 분리
2. SplashContext 생성
3. 프로필 수정 페이지 수정
4. Splash 기능 구현
> ♻️: userContext 분리 및 Splash 기능 수정, 프로필 수정 페이지 수정

- src/components/post/Article.jsx
- src/pages/profile/commentPage/Comment.jsx
- src/pages/profile/commentPage/CommentList.jsx
- src/pages/profile/commentPage/CommentList.scss
- src/pages/profile/commentPage/CommentPage.jsx
1. 포스트 comments 데이터 불러오기 기능 구현
2. 댓글 작성자 클릭시 프로필 페이지로 이동하는 기능 추가
> 🔧 포스트 댓글 데이터 불러오기 구현

- public/index.html
- src/components/button/MoreBtn.jsx
- src/components/button/UserMoreBtn.jsx
- src/components/header/ChatRoomHeader.jsx
- src/components/header/CommonHeader.jsx
- src/components/modal/Modal.scss
- src/components/modal/common/ModalButton.jsx
- src/components/modal/common/ModalFrame.jsx
- src/components/modal/common/ModalPortal.jsx
- src/components/modal/contents/CommentModal.jsx
- src/components/modal/contents/DefaultModal.jsx
- src/components/modal/contents/PostModal.jsx
- src/components/modal/contents/ProductModal.jsx
- src/components/modal/contents/QuitChatModal.jsx
- src/components/post/Article.jsx
- src/pages/chat/chatPage/ChatPage.jsx
- src/pages/chat/chatRoom/ChatRoom.jsx
- src/pages/profile/Profile.jsx
- src/pages/profile/commentPage/Comment.jsx
- src/pages/profile/commentPage/CommentPage.jsx
- src/pages/profile/userProduct/Product.jsx
- src/pages/profile/userProduct/UserProduct.scss
모달창 컴포넌트 생성하고 필요한 페이지에 적용했습니다.
개선해야할 점 
1. accountname 확인하고 모달 contents 구분 
2. 모달 버튼 클릭시 alert 추가 , 기능 추가 구현
3. 모달창 영역 클릭했을 때도 모달창 닫히는 부분 수정
> 🔧 페이지별로 모달창 적용

- src/pages/profileEdit/ProfileEdit.jsx
- src/pages/profileEdit/ProfileEditInfo.jsx
1. 프로필수정 할때 이미지만 변경 가능하게 수정했습니다.
2. 프로필을 수정 할때 accountname을 로컬스토리지에도 저장하게 했습니다.
> 🧹: 프로필수정 할때 이미지만 변경 가능하게 수정했습니다.

- src/App.jsx
- src/components/footer/CommentFooter.jsx
- src/components/footer/PageFooter.scss
- src/context/ImageTestContext.jsx
- src/pages/follow/FollowList.jsx
- src/pages/follow/User.jsx
- src/pages/follow/UserList.jsx
- src/pages/home/Home.jsx
- src/pages/logIn/signUp/SignUp.jsx
- src/pages/logIn/signUp/emailSignUp/EditAccount.jsx
- src/pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
- src/pages/logIn/signUp/profileSet/EditInfo.jsx
- src/pages/logIn/signUp/profileSet/ProfileSet.jsx
- src/pages/logIn/signUp/profileSet/UploadPic.jsx
- src/pages/profile/Profile.jsx
- src/pages/profile/commentPage/Comment.jsx
- src/pages/profile/commentPage/CommentList.jsx
- src/pages/profile/commentPage/CommentPage.jsx
- src/pages/profile/profileHeader/ProfileHeader.jsx
- src/pages/profile/userPost/UserPost.jsx
1. 이미지 예외처리 기능(정규 표현식 검증) Context 함수로 필요한 페이지에서 사용할 수 있도록 컴포넌트화
2. import문 react -> react-router-dom -> context -> axios -> components -> pages component -> img -> scss 순으로 정렬하였습니다.
> 🔧 이미지 예외처리 기능 Context 컴포넌트화 및 적용

- src/App.jsx
- src/context/UserContext.jsx
- src/pages/emailLoginPage/EmailLoginPage.jsx
- src/pages/homePage/HomePage.jsx
- src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
- src/pages/signUpPage/profileSet/EditInfo.jsx
token의 초기값이 'Bearer ' 여서, 원래 token ? 또는 token && 로 조건부 실행 되던 코드에 오류가 있었습니다.
실제 로컬스토리지에서 받아오는 token 값과, "Bearer "이 붙은 값을 분리해주어 해결하였습니다.
> 🧹 토큰 없이 서버에 요청 보내는 이슈 수정

- src/components/modal/Modal.scss
- src/components/modal/alert/alertBase/CancelBtn.jsx
- src/components/modal/alert/alerts/DeleteAlert.jsx
- src/components/modal/alert/alerts/LogoutAlert.jsx
- src/components/modal/alert/alerts/QuitChatAlert.jsx
- src/components/modal/alert/alerts/ReportAlert.jsx
- src/components/modal/modalBase/ModalLink.jsx
- src/components/modal/modals/CommentModal.jsx
- src/components/modal/modals/DefaultModal.jsx
- src/components/modal/modals/PostModal.jsx
- src/components/modal/modals/ProductModal.jsx
- src/components/modal/modals/QuitChatModal.jsx
- src/components/post/Article.jsx
- src/hooks/useDelete.jsx
- src/hooks/useReport.jsx
- src/pages/postDetailPage/comment/Comment.jsx
- src/pages/postDetailPage/comment/CommentList.jsx
- src/pages/profilePage/userPost/UserPost.jsx
1. 게시글, 댓글 신고 삭제 기능 구현 
2. account 에 따라 다른 모달창 ui 구현 
Todo :
comment는 삭제 후 바로 리스트에 반영이 되지만 , 
post는 리렌더링을 해야 리스트에 반영이 되어서 추가 구현 필요
> 🔧 댓글, 게시글 삭제 및 신고 기능 구현

- src/components/button/LikeBtn.jsx
- src/components/splash/Splash.jsx
- src/pages/homePage/HomePage.jsx
- src/pages/profilePage/userProduct/Product.jsx
- src/pages/uploadPostPage/UploadPostPage.jsx
- src/pages/uploadPostPage/UploadPostPage.scss
- src/pages/uploadPostPage/previewImgList/PreviewImgList.scss
splash 컴포넌트를 불러오면 조건문이 잘못 작성되어 있어서 화면에 세션스토리지에서 getItem 한 값이 나오는 오류가 있었고, 수정 완료했습니다. 짧은 코드라 바로 머지하도록 하겠습니다.
> 🧹 splash 코드 화면에 세션스토리지 값 뜨는 오류 수정

- src/pages/profileEditPage/ProfileEditPage.jsx
> 🐞: 프로필수정 페이지 기존 프로필 데이터 수신 오류 해결

- src/components/modal/modalBase/ModalBtn.jsx
- src/components/modal/modalBase/ModalLink.jsx
- src/components/modal/modals/PostModal.jsx
- src/components/modal/modals/ProductModal.jsx
- src/pages/uploadProductPage/UploadProductPage.jsx
불필요한 코드와 주석 삭제하고 설명 주석 추가하였습니다.
> 🧹 불필요한 코드 삭제 및 정리

- README.md
- src/App.jsx
- src/components/modal/modals/CommentModal.jsx
- src/components/modal/modals/PostModal.jsx
- src/components/modal/modals/ProductModal.jsx
- src/pages/chatRoomPage/ChatRoomPage.jsx
- src/pages/postDetailPage/PostDetailPage.jsx
- src/pages/profilePage/ProfilePage.jsx
- src/pages/updatePostPage/UpdatePostPage.jsx
- src/pages/updateProductPage/UpdateProductPage.jsx
- src/pages/updateProuctPage/UpdateProductPage.jsx
- src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
- 상품 등록 페이지의 웹사이트 주소 input 창에 "http://www" 를 기본 value 로 넣어줬으나, 
웹사이트 링크는 복사, 붙여넣기 하는 경우가 대부분이라 불필요할 것 같다는 의견에 제거해주었습니다. 
- 게시글과 상품 수정 페이지를 생성하였고 페이지 이동을 위한 라우트를 추가해주었습니다.
- 모달창의 수정 버튼 링크를 해당 라우트로 변경해주었습니다.
> 상품 웹사이트 기본 인풋값, 불필요한 코드 제거, 수정페이지 생성, 라우트 추가

- src/components/footer/CommentFooter.jsx
- src/components/modal/modalBase/ModalLink.jsx
- src/components/user/UserInfoBox.scss
- src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
- src/pages/profilePage/userProduct/UserProduct.jsx
- src/pages/signUpPage/emailSignUp/EditAccount.jsx
- src/pages/signUpPage/profileSet/EditInfo.jsx
- src/pages/updatePostPage/UpdatePostPage.jsx
- src/pages/updateProductPage/UpdateProductPage.jsx
- src/pages/uploadPostPage/UploadPostPage.jsx
- src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
1. Follower, Following 페이지에서 유저의 accountname 과 subtext 가 overflow 될 시 ellipsis 처리
2. 상품 등록 페이지, 게시글 등록 페이지, 회원가입 페이지, 회원정보 입력 페이지, 각각의 수정페이지에 인풋 포커징 기능 추가 
3. 불필요한 코드 제거
> Follow 컴포넌트 ui 개선, 인풋 포커징 기능 추가

- src/assets/iccon-img-layers.svg
- src/pages/profilePage/userPost/PostAlbum.jsx
- src/pages/profilePage/userPost/UserPost.jsx
- src/pages/profilePage/userPost/UserPost.scss
1. 같은 데이터에서 앨범뷰인 경우 style만 바꾸려고 했는데, 리스트뷰일때 무한스크롤 기능 때문에 이미지가 일부만 로딩 되는 문제 발견..
2. 앨범뷰 클릭하면 image가 있는 데이터만 따로 받아오도록 기능 추가
3. 다중 이미지인 경우 style 다르게 적용 
4. 이미지 클릭시 postView 페이지 이동
> 🔧 포스트 앨범뷰 데이터 받아오기 및 UI 구현

- src/components/button/FollowBtn.scss
- src/components/button/ProfileButton.scss
- src/components/modal/Modal.scss
- src/pages/updatePostPage/UpdatePostPage.jsx
- src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
1. 글만 있는 게시글을 불러왔을 때 빈 이미지 상자가 나타나는 오류 개선
2. 기존의 이미지가 초기화되는 문제 개선
3. 프로필 페이지에서 프로필 수정, 상품 등록 버튼 활성화 UI 적용 
4. 모달 css 수정
5. 상품등록 placeholder "http://www.형식으로 입력해주세요." -> "http:// 형식으로 입력해주세요." 로 변경
> 게시글 이미지 수정기능 개선 및 추가 구현, 버튼 활성화 UI 적용, 기타 CSS 수정

- public/index.html
- src/components/button/FollowBtn.scss
- src/components/button/ProfileButton.scss
- src/components/style/reset.scss
- 모바일로 들어갔을 때 인풋창 클릭시 확대되는 부분 개선
- 아이폰 인풋창 기본 스타일 reset
- 버튼 박스쉐도우 수정
> 🎨 모바일 대응 css 적용 , 버튼 스타일 수정

- src/components/post/Article.jsx
- src/components/post/Post.scss
1. 이미지 비율 수정했습니다.
2. 이미지 여백 추가했습니다.
> 🎨: 이미지 Swiper UI 수정

- src/components/footer/CommentFooter.jsx
props지옥을 벗어나지 못하고.. 급한대로 DOM조작하여 comment count 실시간 반영되도록 눈속임(?)조치 취하였습니다......
> 🧹 댓글 실시간 코멘트 count up 기능 추가

- src/components/notFound/NotFound.jsx
- src/components/notFound/NotFound.scss
- src/pages/updatePostPage/UpdatePostPage.jsx
- 게시글 수정 페이지에서 새로운 input 이 작성되지 않는 오류 수정
- notFound 페이지에 홈으로 이동 버튼 추가
> 게시글 수정 페이지, notFound 페이지 개선

- src/pages/updatePostPage/UpdatePostPage.jsx
- src/pages/updateProductPage/UpdateProductPage.jsx
상품, 게시글 수정 페이지에 로딩중, rejected 상태 추가
> 🎨 수정 페이지 pending, rejected 상태 추가

- src/pages/uploadProductPage/UploadProductPage.jsx
- src/pages/uploadProductPage/UploadProductPage.scss
- src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
- 기존에는 이미지를 등록하지 않아도 업로드 버튼이 활성화 되었는데 , 이미지를 포함한 모든 인풋값을 입력했을 때 업로드 버튼이 활성화되게끔 수정하였습니다. 
- 상품 가격의 천만단위가 넘어가면 경고문구를 띄우도록 추가하였습니다.
> 🧹 상품 가격 limit 문구 추가 , 모든 인풋 입력시 업로드 버튼 활성화

- src/components/header/SearchHeader.jsx
- src/pages/searchUserPage/SearchUserPage.jsx
> ♻유저 검색 키워드 입력시 setTimeout으로 쿼리 중복 요청 감소
